import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import React from 'react';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className='h-screen flex flex-col bg-zinc-800'>
          <div className='flex-1'>
            {/* Top section (1/4 black) */}
            <section className='h-1/4 w-full bg-black flex justify-center items-center'>
              <h1 className='font-bold font-sans text-white text-3xl'>
                <span className='text-blue-400'>Todo </span>
                <span className='text-purple-400'>App</span>
              </h1>
            </section>

            {/* Bottom section (3/4 gray) */}
            <section className='flex-1 bg-gray-600'>{children}</section>
          </div>
        </main>
      </body>
    </html>
  );
}
